name: skygear_sdk_flutter
version: 0.1.0
description: Experimental. Use it at your own risk.
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  meta: '>=1.0.0 <2.0.0'
  punycode: '0.1.0'
  crypto: '>=2.0.0 <3.0.0'
  dio: '>=3.0.0 <4.0.0'
  flutter:
    sdk: flutter
  flutter_secure_storage: '>=3.0.0 <4.0.0'
  uni_links: '0.2.0'
  url_launcher: '>=5.0.0 <6.0.0'
dev_dependencies:
  test: '>=1.0.0 <2.0.0'
  flutter_test:
    sdk: flutter
